version: '3.1'
services:
  web:
    build: .
    image: mygoapp
    restart: always
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    links:
      - db
  db:
    build: ./db/
    image: array_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: testDB
    volumes:
      - ./db/Users_Table.sql:/docker-entrypoint-initdb.d/Users_Table.sql
